name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'  # This runs the workflow once a day at 9:00 AM UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow as well

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
- name: Create a commit with your email
  run: |
    git config user.name "DevSync Automation"
    git config user.email "22f3002257@ds.study.iitm.ac.in"
    echo "Commit made at $(date)" >> timestamp.txt
    git add timestamp.txt
    git commit -m "Automated daily commit" || echo "Nothing to commit"
    git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:main


    - name: Verify Commit
      run: |
        echo "Verifying commit..."
        git log -n 1
