name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'  # Daily at 9:00 AM UTC
  workflow_dispatch:      # Allow manual trigger

jobs:
  daily_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a commit with your email (22f3002257@ds.study.iitm.ac.in)
        run: |
          git config user.name "DevSync Automation"
          git config user.email "22f3002257@ds.study.iitm.ac.in"

          echo "Commit made at $(date)" >> timestamp.txt

          git add timestamp.txt
          git commit -m "Automated daily commit" || echo "Nothing to commit"

          # ✅ Use GITHUB_TOKEN for push authentication (this is key!)
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git push origin HEAD:main

      - name: Verify Commit
        run: git log -1
