name: Daily Timestamp Commit

on:
  schedule:
    - cron: '0 10 * * *'  # Runs daily at 9:00 AM UTC
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Git config
        run: |
          git config user.name "commit Automation"
          git config user.email "uditv120@gmail.com"

      - name: Update timestamp
        run: |
          echo "Commit at $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> timestamp2.txt

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git add timestamp.txt
          git commit -m "Automated commit: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" || echo "No changes to commit"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}
          git push origin HEAD:main
