name: Daily Commit

on:
  schedule:
    - cron: '0 9 * * *'  # This runs the workflow once a day at 9:00 AM UTC
  workflow_dispatch:  # Allows you to manually trigger the workflow as well

jobs:
  daily_commit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Create a commit with your email
      run: |
        # Set up Git configuration with your email
        git config --global user.name "DevSync Automation"
        git config --global user.email "22f3002257@ds.study.iitm.ac.in"
        
        # Create or modify a file to simulate changes (e.g., timestamp.txt)
        echo "Commit made at $(date)" >> timestamp.txt
        
        # Stage, commit, and push changes
        git add timestamp.txt
        git commit -m "Automated daily commit"
        git push

    - name: Verify Commit
      run: |
        echo "Verifying commit..."
        git log -n 1
