name: Bi-Daily Timestamp Commit

on:
  schedule:
    # Runs every 2 days at 10:00 UTC
    - cron: '0 10 */2 * *'
  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Update timestamp
        run: |
          date > timestamp.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add timestamp.txt
          git commit -m "chore: update timestamp [skip ci]" || echo "No changes to commit"
          git push
